export let movies = [
	{ content: "Ae dil h mushkil", type: "movie" },
	{ content: "Chandani chowk to china", type: "movie" },
	{ content: "Raabta", type: "movie" },
	{ content: "Saaho", type: "movie" },
	{ content: "Fukrey", type: "movie" },
	{ content: "Happy new year", type: "movie" },
	{ content: "PK", type: "movie" },
	{ content: "2 states", type: "movie" },
	{ content: "ABCD 2", type: "movie" },
	{ content: "Secret superstar", type: "movie" },
	{ content: "Badhaai ho", type: "movie" },
	{ content: "Malang", type: "movie" },
	{ content: "Dhoom2", type: "movie" },

	{ content: "Tools of titans", type: "book" },
	{ content: "Tribe of mentors", type: "book" },
	{ content: "Atomix habits", type: "book" },
	{ content: "Psychology of money", type: "book" },
	{ content: "Neuromancer by William Gibson", type: "book" },
	{ content: "The martian", type: "book" },
	{ content: "Snow crash", type: "book" },
	{ content: "The mom test", type: "book" },
	{ content: "The first principles", type: "book" },
	{ content: "Dune series", type: "book" },
	{
		content:
			"Zen and the Art of Motorcycle Maintenance: An Inquiry Into Values",
		type: "book",
	},
	{ content: "Stranger in a Strange Land", type: "book" },
	{ content: "Delivering Happiness By Tony Hsieh", type: "book" },
	{ content: "The purple cow", type: "book" },
	{ content: "Great by Choice", type: "book" },
	{ content: "Brave New World", type: "book" },
	{
		content: "Sell or Be Sold: How to Get Your Way in Business and in Life",
		type: "book",
	},
];

